version: '3.8'
services:
  solr:
    container_name: chainguide-solr
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - chainguide
      - ./example-data/load-example-data.sh
    networks:
      - chainguide-net
  chainguide:
    container_name: chainguide
    image: almaak/chainguide:latest
    ports:
      - "80:80"
    environment:
      - SOLR_HOST=chainguide-solr
      - SOLR_PORT=8983
    networks:
      - chainguide-net
volumes:
  data:
networks:
  chainguide-net:
